# Generated by Django 2.0 on 2017-12-26 22:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_emp', models.CharField(max_length=200)),
                ('email_emp', models.EmailField(max_length=254)),
                ('cargo_emp', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo_pieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equipo', models.CharField(max_length=10, unique=True)),
                ('nombre_equipo', models.CharField(max_length=50)),
                ('tipo_eq', models.CharField(choices=[('PZ', 'Pieza'), ('EQ', 'Equipo')], max_length=2)),
                ('date_eq', models.DateTimeField(default=django.utils.timezone.now)),
                ('padre_eq', models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.CASCADE, to='control.Equipo_pieza')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mant', models.CharField(max_length=15, unique=True)),
                ('nombre_mant', models.CharField(max_length=50)),
                ('actividad_mant', models.CharField(max_length=200)),
                ('padre_mant', models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.CASCADE, to='control.Mantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento_Pieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mantpiz', models.CharField(max_length=15, unique=True)),
                ('frecuencia_mt', models.PositiveSmallIntegerField(default=0)),
                ('fech_prox_mt', models.DateTimeField(default=django.utils.timezone.now)),
                ('notificar_mt', models.BooleanField(default=True)),
                ('mantenimiento_mt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Mantenimiento')),
                ('pieza_mt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Equipo_pieza')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rmt', models.CharField(choices=[('CRT', 'Correctivo'), ('PRV', 'Preventivo')], max_length=3)),
                ('fech_ini_rmt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de inicio')),
                ('fech_fin_rmt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de finalizacion')),
                ('observacion_rmt', models.CharField(max_length=25)),
                ('defecto_rmt', models.CharField(max_length=25)),
                ('costo_rmt', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('encargados_rmt', models.ManyToManyField(to='control.Empleados')),
                ('pieza_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Mantenimiento_Pieza')),
            ],
        ),
    ]
